name: Pypi Deploy

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
    branches:
      - main

jobs:
  pypi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get version number
        id: get_version
        run: |
          echo ::set-output name=VERSION::$(python3 setup.py --version)

      - name: Check version matches tag
        id: check_version
        run: |
          if [ "v${{ steps.get_version.outputs.VERSION }}" != "${GITHUB_REF#refs/tags/v}" ]; then
            echo "Version number in setup.py does not match tag"
            exit 1
          fi

      - name: conventional changelog action
        id: changelog
        # https://github.com/TriPSs/conventional-changelog-action
        uses: TriPSs/conventional-changelog-action@latest
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          skip-git-pull: "true"
          skip-version-file: "true"
          output-file: "false"

      - name: Build
        run: |
          python3 -m pip install --upgrade pip && \
          pip install -r dev-requirements.txt && \
          python3 setup.py sdist bdist_wheel

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref }}
          body: ${{steps.changelog.outputs.clean_changelog}}
          draft: false
          prerelease: false

      - name: Upload tar to release
        id: upload-release-tar
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/palm-${{steps.get_version.outputs.VERSION}}.tar.gz
          asset_name: palm--${{steps.get_version.outputs.VERSION}}.tar.gz
          asset_content_type: application/tar+gzip

      - name: Upload wheel to release
        id: upload-release-wheel
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/palm-${{steps.get_version.outputs.VERSION}}-py3-none-any.whl
          asset_name: palm--${{steps.get_version.outputs.VERSION}}-py3-none-any.whl
          asset_content_type: application/wheel

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}